name: Build Android (Capacitor)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web (Vite)
        run: npm run build

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Add Android platform (Capacitor)
        run: npx cap add android

      - name: Sync Android
        run: npx cap sync android

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Sign Release Build (if secrets are present)
        if: |
          secrets.ANDROID_KEYSTORE_BASE64 != '' &&
          secrets.ANDROID_KEYSTORE_PASSWORD != '' &&
          secrets.ANDROID_KEY_ALIAS != '' &&
          secrets.ANDROID_KEY_ALIAS_PASSWORD != ''
        uses: ./.github/actions/android-sign
        with:
          keystore-base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          keystore-password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          key-alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          key-alias-password: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}

      - name: Upload Signed Release APK (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk-signed
          path: android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: ignore

      - name: Create GitHub Release and attach artifacts (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            android/app/build/outputs/bundle/release/app-release.aab
            android/app/build/outputs/apk/release/app-release.apk
            android/app/build/outputs/apk/debug/app-debug.apk
