name: Build iOS (Capacitor)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web (Vite)
        run: npm run build

      - name: Add iOS platform (Capacitor)
        run: npx cap add ios

      - name: Sync iOS
        run: npx cap sync ios

      - name: Install CocoaPods
        working-directory: ios/App
        run: |
          sudo gem install cocoapods --no-document || true
          pod install --repo-update

      - name: Check signing secrets
        id: secrets
        shell: bash
        run: |
          if [[ -n "${{ secrets.IOS_CERT_P12_BASE64 }}" && -n "${{ secrets.IOS_CERT_PASSWORD }}" && -n "${{ secrets.IOS_MOBILEPROVISION_BASE64 }}" && -n "${{ secrets.IOS_TEAM_ID }}" && -n "${{ secrets.IOS_BUNDLE_ID }}" ]]; then
            echo "signing_enabled=true" >> "$GITHUB_OUTPUT"
          else
            echo "signing_enabled=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Build iOS (xcodebuild - Debug)
        run: |
          set -e
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build

      - name: Import code signing certificate (if provided)
        if: steps.secrets.outputs.signing_enabled == 'true'
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_CERT_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_CERT_PASSWORD }}

      - name: Install Provisioning Profile (if provided)
        if: steps.secrets.outputs.signing_enabled == 'true'
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          # macOS base64 uses -D for decode; try multiple flags for compatibility
          (echo "${{ secrets.IOS_MOBILEPROVISION_BASE64 }}" | base64 -D > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision) \
          || (echo "${{ secrets.IOS_MOBILEPROVISION_BASE64 }}" | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision) \
          || (echo "${{ secrets.IOS_MOBILEPROVISION_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision)

      - name: Archive iOS (Release, only when signing is configured)
        if: steps.secrets.outputs.signing_enabled == 'true'
        run: |
          set -e
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM=${{ secrets.IOS_TEAM_ID }} \
            PRODUCT_BUNDLE_IDENTIFIER=${{ secrets.IOS_BUNDLE_ID }} \
            archive

      - name: Create ExportOptions.plist
        run: |
          cat > ExportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>teamID</key>
            <string>${IOS_TEAM_ID}</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

      - name: Export signed IPA (if signing configured)
        if: steps.secrets.outputs.signing_enabled == 'true'
        run: |
          set -e
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/export

      - name: Upload signed IPA (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-signed
          path: build/export/*.ipa
          if-no-files-found: ignore

      - name: Build Release for Simulator and zip .app (fallback when unsigned)
        if: steps.secrets.outputs.signing_enabled != 'true'
        run: |
          set -e
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build/DerivedData \
            build
          cd build/DerivedData/Build/Products/Release-iphonesimulator
          ditto -c -k --sequesterRsrc --keepParent App.app ../../../../App-simulator.zip

      - name: Upload unsigned artifacts (simulator build)
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: |
            build/DerivedData/Build/Products/Release-iphonesimulator/App.app
            build/App-simulator.zip
          if-no-files-found: ignore

      - name: Create GitHub Release and attach artifacts (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/export/*.ipa
            build/App-simulator.zip
